# Generated by Django 4.0.10 on 2024-01-26 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boardCategories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petCategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, max_length=550, null=True)),
                ('viewCount', models.PositiveIntegerField(default=0, editable=False)),
                ('postImage', models.URLField(blank=True, null=True)),
                ('boardAnimalTypes', models.ManyToManyField(related_name='posts', to='petCategories.pet')),
                ('categoryType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='boardCategories.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, help_text='댓글 내용', max_length=150, null=True)),
                ('parent_comment', models.ForeignKey(blank=True, help_text='댓글 인지 대댓글인지 구분 토글, if parent_comment==null: 댓글, else: 대댓글', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment')),
                ('post', models.ForeignKey(blank=True, help_text='댓글이 달릴 게시글의 pk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='posts.post')),
                ('user', models.ForeignKey(help_text='댓글 작성자의 pk', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
