# Generated by Django 4.0.10 on 2023-12-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
