# Generated by Django 4.0.10 on 2024-01-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('posts', '0002_rename_user_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_address', to='addresses.address'),
        ),
    ]
