# Generated by Django 4.0.10 on 2023-12-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postImage',
        ),
    ]
