# Generated by Django 4.0.10 on 2023-12-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
