# Generated by Django 4.0.10 on 2024-01-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_alter_address_regiondepth2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='regionDepth2',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
