# Generated by Django 4.0.10 on 2023-06-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='regionDepth3',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
