# Generated by Django 4.0.10 on 2024-01-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_regiondepth3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
