databases:
  - name: petmo_back_seed_db
    databaseName: petmo_back_seed_db
    user: petmo_back_seed_db
    region: singapore

services:
  - type: web
    name: petmo_back_seed_db
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: petmo_back_seed_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4