# Generated by Django 4.0.10 on 2023-12-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_animaltypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animalTypes',
            field=models.CharField(choices=[('강아지', '강아지'), ('고양이', '고양이'), ('물고기', '물고기'), ('햄스터', '햄스터'), ('파충류', '파충류'), ('토끼', '토끼'), ('새2', '새2'), ('기타', '기타'), ('전체', '전체')], max_length=255),
        ),
    ]
