# Generated by Django 4.0.10 on 2024-01-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardCategoryType', models.CharField(choices=[('자유', '자유'), ('반려질문', '반려질문'), ('반려고수', '반려고수'), ('장소후기', '장소후기'), ('축하해요', '축하해요'), ('반려구조대', '반려구조대')], max_length=255)),
            ],
        ),
    ]
